/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:4b76968a-0ef0-4bbc-9c75-c42673dd4395",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_ly1v1gjyC",
  aws_user_pools_web_client_id: "6pc4slhlndcvbvp4il13rmdofj",
  oauth: {
    domain:
      "taskauthenticationb62ad0a8-b62ad0a8-dev.auth.us-east-2.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "https://task-manager-six-lovat.vercel.app",
    redirectSignOut: "https://task-manager-six-lovat.vercel.app",
    responseType: "code",
  },

  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: ["GOOGLE"],
  aws_cognito_signup_attributes: ["EMAIL", "FAMILY_NAME", "GIVEN_NAME"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
